### ISSUE TITLE
CC starting Rfactor 2 64 causing Mqtt failure due to #

### ISSUE THREAD

**Issue by MagictapMW** [b4mad/racing#145]
Automobilista2, Raceroom & AC64 all start in CC without Mqtt failing. Rfactor2 causing Mqtt to fail with below messages in the console.

10:06:46.843 : Event Mqtt threw exception The character '#' is not allowed in topics. stack    at MQTTnet.Protocol.MqttTopicValidator.ThrowIfInvalid(String topic)
   at MQTTnet.Protocol.MqttTopicValidator.ThrowIfInvalid(MqttApplicationMessage applicationMessage)
   at MQTTnet.Client.MqttClient.PublishAsync(MqttApplicationMessage applicationMessage, CancellationToken cancellationToken)
   at CrewChiefV4.Events.Mqtt.triggerInternal(GameStateData previousGameState, GameStateData currentGameState) in C:\projects\crewchief_c_sharp\CrewChiefV4\CrewChiefV4\Events\Mqtt.cs:line 253
   at CrewChiefV4.CrewChief.triggerEvent(String eventName, AbstractEvent abstractEvent, GameStateData previousGameState, GameStateData currentGameState) in C:\projects\crewchief_c_sharp\CrewChiefV4\CrewChiefV4\CrewChief.cs:line 1128
10:06:46.843 : This is the first time this event has failed in this session
10:06:46.843 : ********** starting spotter***********
10:06:46.843 : Invoking spotter every 50
10:06:47.228 : There are 1 more events in the queue, playing them...
10:06:47.228 : Playing sounds, events: COMPOUND_smoke_test_spotter
10:06:47.228 : (radio_check_Billy/test)
10:06:47.754 : Event Mqtt has failed 10 times in this session and will be disabled

**Comment by durandom** [comment]
I have fixed this in crewchief
