### ISSUE TITLE
`The character '#' is not allowed in topics` exeception when used with rfactor2

### ISSUE THREAD

**Issue by goern** [b4mad/racing#146]
https://discord.com/channels/850841654327640074/914445482154147860/1050708958836424715

```
[10:42 AM]Matt Webb: hi all. stumbled into this but keen to try make it work. alas after following the install instructions I get this:
[10:43 AM]Matt Webb: Event Mqtt threw exception The character '#' is not allowed in topics. stack    at MQTTnet.Protocol.MqttTopicValidator.ThrowIfInvalid(String topic)
   at MQTTnet.Protocol.MqttTopicValidator.ThrowIfInvalid(MqttApplicationMessage applicationMessage)
   at MQTTnet.Client.MqttClient.PublishAsync(MqttApplicationMessage applicationMessage, CancellationToken cancellationToken)
   at CrewChiefV4.Events.Mqtt.triggerInternal(GameStateData previousGameState, GameStateData currentGameState) in C:\projects\crewchief_c_sharp\CrewChiefV4\CrewChiefV4\Events\Mqtt.cs:line 253
   at CrewChiefV4.CrewChief.triggerEvent(String eventName, AbstractEvent abstractEvent, GameStateData previousGameState, GameStateData currentGameState) in C:\projects\crewchief_c_sharp\CrewChiefV4\CrewChiefV4\CrewChief.cs:line 1128
09:40:16.990 : This is the first time this event has failed in this session
[10:43 AM]goern.b4mad.eth: Hi Matt 👍
[10:43 AM]Matt Webb: hiya
[10:44 AM]goern.b4mad.eth: I assume it’s all the latest and greatest crew chief versions?
[10:44 AM]Matt Webb: yes sir
[10:44 AM]Matt Webb: 4.16.3.4
[10:44 AM]goern.b4mad.eth: And did you follow the install like yesterday?! I think there was an update to the config..
[10:44 AM]Matt Webb: about 15 mins ago
[10:45 AM]goern.b4mad.eth: Cool!
[10:45 AM]Matt Webb: i did over right the mqtt json so cant go back now ;O)
[10:45 AM]Matt Webb: overwrite...
[10:45 AM]goern.b4mad.eth: Does your driver name contain a # ?
[10:45 AM]Matt Webb: nope. Mattw
[10:46 AM]Matt Webb: ah.....i think I know whats happened. I put Mattw in the mqtt driver name...but
[10:46 AM]goern.b4mad.eth: Strange error that is, let’s ping @durandom he wrote that part
[10:46 AM]Matt Webb: I did a windows refresh yesterday and reinstalled CC...I havent put my name in the actual name bit!! bloody stupid sorry
[10:47 AM]goern.b4mad.eth: Null problemo, that’s what i do all the time 😁
[10:48 AM]Matt Webb: trying again. Will report back. Thank you
[10:48 AM]goern.b4mad.eth: cool! Thanks
[10:48 AM]goern.b4mad.eth: Let’s see what features are missing to make it a good tool for you!
[10:49 AM]Matt Webb: still fails

Event Mqtt has failed 10 times in this session and will be disabled
[10:49 AM]Matt Webb: same # erro
[10:49 AM]Matt Webb: r
[10:50 AM]goern.b4mad.eth: ack, let me check if you cc is working
[10:50 AM]Matt Webb: hang on, restarted and it might be working...doing laps
[10:51 AM]Matt Webb: ah, nope, it connects to mqtt when I load CC, but as soon as I start CC in rf2 mode it gets the error
[10:52 AM]Matt Webb: doesnt happen if I select games Automobilista2 and Raceroom, just rfactor2 64
[10:55 AM]goern.b4mad.eth: ja, I see, for AC 64bit it seems to work
[10:56 AM]Matt Webb: can confirm that works for me also to
```

/kind bug
/assign @durandom

**Comment by durandom** [comment]
looks like we need to make sure we pass https://github.com/dotnet/MQTTnet/blob/73d681bc1f978c4e6cf03266fcd1fb4a30a5d205/Source/MQTTnet/Protocol/MqttTopicValidator.cs#L22-L41

right now I'm only replacing a `/` in https://gitlab.com/mr_belowski/CrewChiefV4/-/blob/master/CrewChiefV4/Events/Mqtt.cs#L226-231

**Comment by durandom** [comment]
I have fixed this in crewchief
