### ISSUE TITLE
fastlap app not available?!

### ISSUE THREAD

**Issue by goern** [b4mad/racing#430]
on head of main...

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/fastlap/

Django Version: 4.2.5
Python Version: 3.10.12
Installed Applications:
['allauth',
 'allauth.account',
 'allauth.socialaccount.providers.openid',
 'allauth.socialaccount.providers.discord',
 'allauth.socialaccount.providers.github',
 'allauth.socialaccount.providers.google',
 'allauth.socialaccount.providers.microsoft',
 'allauth.socialaccount.providers.reddit',
 'allauth.socialaccount.providers.steam',
 'allauth.socialaccount.providers.twitch',
 'allauth.socialaccount',
 'bootstrap4',
 'fontawesomefree',
 'crispy_bootstrap4',
 'crispy_forms',
 'django_extensions',
 'django_plotly_dash.apps.DjangoPlotlyDashConfig',
 'django.contrib.admin',
 'django_admin_listfilter_dropdown',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'dpd_static_support',
 'explorer',
 'django_prometheus',
 'telemetry.apps.TelemetryConfig']
Installed Middleware:
['django_prometheus.middleware.PrometheusBeforeMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django_plotly_dash.middleware.BaseMiddleware',
 'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']


Template error:
In template /var/home/goern/Source/github.com/b4mad/racing/components/paddock/paddock/templates/fastlap.html, error at line 14
   Unable to find stateless DjangoApp called Fastlap
   4 : 
   5 : {%block title%}Pit Crew{%endblock%}
   6 : 
   7 : {%block content%}
   8 : <h1>#B4mad Racing Pit Crew</h1>
   9 : <div class="card border-dark">
   10 :   <div class="card-body">
   11 :     <div class="container">
   12 :       <div class="row">
   13 :         <div class="col-sm-12">
   14 :           <div class=" {%plotly_class name="Fastlap"%} ">
   15 :             {%plotly_direct name="Fastlap" %}
   16 :           </div>
   17 :         </div>
   18 :       </div>
   19 :     </div>
   20 :   </div>
   21 : </div>
   22 : {%endblock%}
   23 : 

Traceback (most recent call last):
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/paddock/views.py", line 197, in fastlap
    return render(request, template_name=template_name, context=context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 181, in plotly_class
    da, app = _locate_daapp(name, slug, da)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 58, in _locate_daapp
    da, app = DashApp.locate_item(name, stateless=True, cache_id=cache_id)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django_plotly_dash/models.py", line 227, in locate_item
    dash_app = find_stateless_by_name(ident)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django_plotly_dash/models.py", line 84, in find_stateless_by_name
    dash_app = get_stateless_by_name(name)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django_plotly_dash/models.py", line 40, in get_stateless_by_name
    return get_local_stateless_by_name(name)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django_plotly_dash/dash_wrapper.py", line 131, in get_local_stateless_by_name
    raise KeyError("Unable to find stateless DjangoApp called %s"%name)

Exception Type: KeyError at /fastlap/
Exception Value: 'Unable to find stateless DjangoApp called Fastlap'

```

/kind bug
/priority critical-urgent
/assign durandom

**Comment by durandom** [comment]
fixed in #449
