### ISSUE TITLE
pitcrew throws exception

### ISSUE THREAD

**Issue by goern** [b4mad/racing#62]
using a47b45ad6dc438537631a73a9af08443b0d515fc pitcrew threw an exception:

```
DEBUG:root:new session crewchief/goern/1666692415/iRacing/summit summit raceway/Ferrari 488 GT3 Evo 2020/LonePractice
Traceback (most recent call last):
  File "/home/goern/Source/github.com/b4mad/racing/pitcrew/./app.py", line 23, in <module>
    mqtt.run()
  File "/home/goern/Source/github.com/b4mad/racing/pitcrew/mqtt.py", line 102, in run
    self.mqttc.loop_forever()
  File "/home/goern/.local/share/virtualenvs/pitcrew-wsNBG5uX/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/home/goern/.local/share/virtualenvs/pitcrew-wsNBG5uX/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/home/goern/.local/share/virtualenvs/pitcrew-wsNBG5uX/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/goern/.local/share/virtualenvs/pitcrew-wsNBG5uX/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/goern/.local/share/virtualenvs/pitcrew-wsNBG5uX/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/goern/.local/share/virtualenvs/pitcrew-wsNBG5uX/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/goern/.local/share/virtualenvs/pitcrew-wsNBG5uX/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/goern/Source/github.com/b4mad/racing/pitcrew/mqtt.py", line 74, in on_message
    response = self.coach.get_response(meters)
  File "/home/goern/Source/github.com/b4mad/racing/pitcrew/coach.py", line 39, in get_response
    if self.msg['corner'] != brakepoint['corner']:
TypeError: 'NoneType' object is not subscriptable
DEBUG:root:loading brakepoints from /home/goern/Source/github.com/b4mad/racing/pitcrew/Ferrari 488 GT3 Evo 2020-summit summit raceway.csv
```

**Comment by goern** [comment]
fixed by cd46dadabb1b645b4134b0812cfd36092cd06ff8
/close
